### PR TITLE
Basic events: psOpen, psClose, psBeforeOpen, psBeforeClose; CSS animation support

### PR DESCRIPTION
**Pull request by duzun**
I added few basic events and also fixed the `README.MD` to close issue #2

### CODE REVIEW

**Comment by Nilpo** [comment]
Should we use callbacks and events at the same time.  I'm not against implementing events, but having both will seem overly confusing for some people.

**Comment by duzun** [comment]
I think it is natural to have an option for callbacks, as it is with DOM elements:

```javascript
a.onclick = function(){...}
a.addEventListener(function(){...})
a.addEventListener(function anotherFunction(){...})
```

Callbacks are easy to use, but you are limited to just one function.
With events, on the other hand, you can have multiple modules listening for the same event.

I think events are required, callback are more like an option to me.

**Comment by duzun** [comment]
I see this PR doesn't get merged ... 
With time I keep adding to my fork and it has more features then described in the title.
For instance this PR closes #17.

P.S. CSS animations are very important especially on mobile devices.

**Comment by Nilpo** [comment]
If and when this is merged, you can update your fork by rebasing from upstream.  Then your commits will again be able to be merged.  That's the beauty of version control.  It's also much easier if you've been using proper branching.

**Comment by duzun** [comment]
My fault with branching :-)
At this point this PR still can be merged without any conflict with fast-forwar.

**Comment by eduardomb** [comment]
Very nice coding, @duzun . I like the new features. 

I see there is a lot of changes and I want to look carefully before I merge it. I also want to keep consistency in the coding style, It's easier to read and maintain the source if we stick to one style from begin to end instead of using comma-first style in some parts and commas at the end in others.

Since you are boosting performance with CSS, I also want to replace the margin animation with some ```transform: translate(...)```. It will make the animation a lot smoother, specially on mobile devices.

I wish I could make these changes and merge the PR right away but right now I don't have much time and It might take me a little while to do so, but I will. Thanks for the big contribution.

**Comment by duzun** [comment]
I changed comma style and made a rebase to include all new commits.

I'm not using `transform` so far, but it works pritty well with `transition`.
There is a special class `.ps-animated` in `jquery.panelslider.css` that animates some metric properties, this way JS just sets the value and CSS animates it.

**Comment by eduardomb** [comment]
@duzun thanks for all the contribution. I finally read all your code, sorry it took this long. I've embraced 100% your idea of animating the panel through **CSS transition**. In fact, I've completely removed **jQuery.animate** on version `1.0.0` and decided that animation and positioning should be handled by user's CSS. I've also implemented an example on _example.html_.

The following commits (regarding to CSS animation) inspired the new approach of version `1.0.0` and can't be merged because now is the user responsibility to implement animation:
- https://github.com/duzun/jquery-panelslider/commit/5a92cf03a85d122c1337054b46ccd9705e6ebc0e
- https://github.com/duzun/jquery-panelslider/commit/5a5a61df70641570dd416627268f4eafb9285fc8
- https://github.com/duzun/jquery-panelslider/commit/7c77aecbaeaa319c1aae4f09f7c5af30633aab13
- https://github.com/duzun/jquery-panelslider/commit/22cb0e7db93bf150e769c445df97f957de8acfa1
- https://github.com/duzun/jquery-panelslider/commit/97045aa05ddf3bf0cca20711a8c2f59eda9249ee

Sorry I didn't notice your **README** fix (https://github.com/duzun/jquery-panelslider/commit/cb8451acfa6e2e33079f23b1d136dae2c0fb84e9) in time and ended up merging the exact same fix (https://github.com/eduardomb/jquery-panelslider/commit/8a01272007ef759235bf842dd62b51c48ae89263) only months latter.

I agree with you that events are better than callbacks. I've cherry picked the following commits regarding to event triggering and squashed into https://github.com/eduardomb/jquery-panelslider/commit/eec87b5cd4b379581d6c8a4d124364218d9c2003:
- https://github.com/duzun/jquery-panelslider/commit/cc2fe94569b7edbb35d9d2b506176d39191f1da3
- https://github.com/duzun/jquery-panelslider/commit/68cec7e9a7ed1f03e0faa139c84e4d11e6834e78
- https://github.com/duzun/jquery-panelslider/commit/11c1ca0c05aaa1796806376cae2ee4525a3a2c87

Finally, I think the support for `ps-in` and `ps-out` classes (https://github.com/duzun/jquery-panelslider/commit/7688da6d897dcefd72a14cf6c17463351b179754)
is too specific and, therefore, should be handled by the user. Thanks to you It can easily be done now using the events `psBeforeOpen`, `psOpen`, `psBeforeClose` and `psClose`.

**Comment by duzun** [comment]
Thank you for a great plugin.
I'm happy I could help improve it.

I'm using it on my personal website https://duzun.me/ to make navigation more friendly on mobile devices, and it works great (v0.3.0).

**Pull request closed without merging**
